project:
  type: website
  output-dir: docs

website:
  title: "Soki Kimura"
  image: img/london.jpg
  favicon: img/favicon.png
  navbar:
    title: false
    logo: img/logo.png
    logo-alt: "Soki Kimura"
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume
      - projects.qmd
    tools:
      - icon: github
        href: https://github.com/sokimura39
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/soki-kimura/
        target: _blank
      - icon: twitter
        href: https://x.com/sokim39
        target: _blank
      - icon: person-circle
        href: https://bsky.app/profile/sokim39.bsky.social
        target: _blank
      - icon: medium
        href: https://medium.com/@sokimura39
        target: _blank
  page-footer: 
    left: "© 2024 Soki Kimura"
    right: 
      - icon: github
        href: https://github.com/sokimura39
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/soki-kimura/
        target: _blank
      - icon: twitter
        href: https://x.com/sokim39
        target: _blank
      - icon: person-circle
        href: https://bsky.app/profile/sokim39.bsky.social
        target: _blank
      - icon: medium
        href: https://medium.com/@sokimura39
        target: _blank
  twitter-card: true
  open-graph: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



