project:
  type: website
  output-dir: docs

website:
  title: "Soki Kimura"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Resume
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/soki-kimura/
      - icon: github
        href: https://github.com/sokimura39
  page-footer: 
    left: "© 2024 Soki Kimura"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/soki-kimura/
      - icon: github
        href: https://github.com/sokimura39

format:
  html:
    theme: yeti
    css: styles.css
    toc: true



